# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [6]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

new_height = np.array(height)
new_weight = np.array(weight)

new_weight

(new_weight / (new_height**2))*730

array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [33]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
def makeMatrix(low,high,shape = None,data_type = float):
    if data_type == int:
        return np.random.randint(low,high,(shape))
    else:
        return np.random.uniform(low, high,(shape))
    
print('float version: \n',makeMatrix(0,10,(3,3)))
print('\n integer version: \n',makeMatrix(0,10,(3,3),int))

float version: 
 [[0.8647326  7.63938353 2.09710959]
 [0.63786932 3.66748777 4.18957531]
 [2.83181443 4.96199408 9.73133588]]

 integer version: 
 [[4 5 6]
 [3 8 6]
 [9 2 5]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [90]:
import csv
import numpy as np

#Test to make sure you have the correct data

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

# Creating Function to open and read CSV data
def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('../day-1/redsox_2017_hitting.txt')
slug2017 = sorted(bs2017['SLG'])
new_slug2017 = np.array(slug2017)
# new_slug2017 = np.delete(new_slug2017,[0,1,2]) -- wanted to delete the smallest values so I could use the subtract operand
# to find the difference between the 2 years.
print(f'Boston 2017 had more SLG, better mins and maxes than 2018: \n {new_slug2017}')

bs2018 = load_data('../day-1/redsox_2018_hitting.txt')
slug2018 = sorted(bs2018['SLG'])
new_slug2018 = np.array(slug2018)
print(f'\n Boston 2018 had lower mins and maxes: \n {new_slug2018}')

Boston 2017 had more SLG, better mins and maxes than 2018: 
 [0.2   0.222 0.243 0.262 0.306 0.328 0.333 0.339 0.342 0.354 0.354 0.387
 0.392 0.402 0.403 0.404 0.424 0.429 0.443 0.459 0.482 0.539 1.   ]

 Boston 2018 had lower mins and maxes: 
 [0.091 0.167 0.261 0.279 0.283 0.311 0.328 0.388 0.389 0.395 0.403 0.411
 0.415 0.433 0.433 0.465 0.507 0.522 0.629 0.64 ]


In [86]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

slg_diff = new_slug2017 - new_slug2018
slg_diff

array([ 0.171     ,  0.139     ,  0.067     ,  0.05399999,  0.05599999,
        0.03100002,  0.02599999, -0.03400001, -0.002     , -0.00300002,
       -0.00099999, -0.00800002, -0.01099998, -0.009     , -0.00400001,
       -0.02200001, -0.04800004, -0.04000002, -0.09000003,  0.36      ],
      dtype=float32)